apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "helix.backend.fullname" . }}-data
  labels:
    {{- include "helix.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.backend.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.backend.size }}
  {{- with .Values.persistence.backend.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
