apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helix.fullname" . }}-seed
  labels:
    {{- include "helix.labels" . | nindent 4 }}
data:
  ambiti.json: |
    {{- .Values.seed.ambiti | toPrettyJson | nindent 4 }}
