apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helix.fullname" . }}-backend-env
  labels:
    {{- include "helix.labels" . | nindent 4 }}
data:
  GEMINI_MODEL: {{ .Values.config.geminiModel | quote }}
  INGESTION_PROVIDER: {{ .Values.config.ingestionProvider | quote }}
  DOCS_FOLDER: {{ .Values.config.docsFolder | quote }}
  CHROMA_HOST: {{ include "helix.chromadb.fullname" . | quote }}
  CHROMA_PORT: {{ .Values.chromadb.service.port | quote }}
