apiVersion: v1
kind: Service
metadata:
  name: {{ include "helix.frontend.fullname" . }}
  labels:
    {{- include "helix.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
  selector:
    {{- include "helix.selectorLabels" (dict "root" . "component" "frontend") | nindent 4 }}
