apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helix.fullname" . }}-backend-secret
  labels:
    {{- include "helix.labels" . | nindent 4 }}
type: Opaque
stringData:
  GEMINI_API_KEY: {{ .Values.secrets.geminiApiKey | quote }}
  CLAUDE_API_KEY: {{ .Values.secrets.claudeApiKey | quote }}
  LLAMAPARSE_API_KEY: {{ .Values.secrets.llamaparseApiKey | quote }}
